### ISSUE TITLE
🪄 Enhancement - Donot update phone number prefix from text box

### ISSUE THREAD

**Issue by rpatidar** [typesnippet/antd-phone-input#90]
### Summary

Its a bit annoying when the phone number changes triggers the country code changes. 

can the country selection be edited only via the drop-down and not via the text box ? this will reduce down the mistakes people can make choosing a wrong country codes because of typos. 

its similar to: https://boyuai.github.io/antd-country-phone-input/demos/basic-usage

**Comment by ArtyomVancyan** [comment]
> Can the country selection be edited only via the drop-down and not via the text box?

@rpatidar, it is interesting to hear users' opinions, but it is a feature that aims to autodetect the country by the dial code. Users who already know the country code may not need the dropdown menu, which is why the dropdown can be disabled, but the described feature does not. Sorry, but this wouldn't be appropriate.
